-- CREATE TABLES
CREATE TABLE UNIVERSITY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   ADDRESS        CHAR(255),
   TYPE           CHAR(20),
   CREATED_AT	  DATE
);

CREATE TABLE DEPARTMENT(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   UNIVERSITY_ID  INT     NOT NULL,
   CLASS_NUMBER   INT,
   CREATED_AT	  DATE
);

-- CRAETE
INSERT INTO UNIVERSITY (ID,NAME,ADDRESS,TYPE) VALUES (1, 'Paul','California', 'Dowlati');
INSERT INTO UNIVERSITY (ID,NAME,ADDRESS,TYPE,CREATED_AT) VALUES (2, 'Allen','Texas', 'Payam-Nour','2007-12-13');
INSERT INTO UNIVERSITY (ID,NAME,ADDRESS,TYPE,CREATED_AT) VALUES (3, 'Teddy','Norway', 'Azad',  '2007-12-13');
INSERT INTO UNIVERSITY (ID,NAME,ADDRESS,TYPE,CREATED_AT) VALUES (4, 'Mark','Rich-Mond ', 'Pardis-Khodgardan', '2007-12-13' );

INSERT INTO DEPARTMENT (ID,NAME,UNIVERSITY_ID,CLASS_NUMBER,CREATED_AT) VALUES (1, 'Software Engineer', 3, '2007-12-13');


-- READ
-- SELECT column1, column2, columnN FROM table_name;
SELECT name, age FROM UNIVERSITY; --PROJECTION
SELECT * FROM COMPANY;
SELECT * FROM COMPANY WHERE name='Paul';
SELECT name, age FROM COMPANY WHERE name='Paul';
SELECT ID, NAME, SALARY FROM COMPANY;
SELECT * FROM UNIVERSITY WHERE address='California';

-- UPDATE
-- UPDATE table_name
-- SET column1 = value1, column2 = value2...., columnN = valueN
-- WHERE [condition];
UPDATE COMPANY SET SALARY = 15000 WHERE ID = 3;
UPDATE university SET created_at = '2007-12-13';
UPDATE university SET created_at = '2007-12-14' WHERE address='California' AND type='Dowlati';

-- DELETE
-- DELETE FROM table_name WHERE [condition];
DELETE FROM UNIVERSITY WHERE ID = 2;

ALTER TABLE university ALTER COLUMN ADDRESS TYPE VARCHAR (20);